### ISSUE TITLE
Update Project Portfolio Page 

### ISSUE THREAD

**Issue by theodorekwok** [AY2122S1-CS2113T-T12-1/tp#101]
- under docs, team there is a project portfolio page.
- in the grading rubrics https://nus-cs2113-ay2122s1.github.io/website/admin/tp-grading.html#2-project-grading-implementation-10-marks  provide the evaluators more POVs to evaluate in addition out of standard reposense functional code evaluation. Can talk about the testing and refactorings to improve code quality etc

**Comment by KVignesh122** [comment]
All PPPs are in.
