### ISSUE TITLE
DG Review

### ISSUE THREAD

**Issue by rafaelperes** [AY2122S1-CS2113T-T12-1/tp#154]
Hello guys. I have some comments about your DG. 
1)Why dashed lines when inheriting from Instrument?
![fig1](https://user-images.githubusercontent.com/1132350/139395129-246e2c01-312c-4664-9e21-761eebd15d2f.PNG)

2) Same here, dashed lines… XYZDecoder to Instrument
![fig2](https://user-images.githubusercontent.com/1132350/139395530-b5d410cd-2904-45ba-a66e-c2046199e085.PNG)

3) "This figure below shows the class diagram of all the commands classes: <>" 
I could not see the class diagram in this case…
4) Why is there a space between :AddStockParser and it’s constructor (white rectangle)?

![fig3](https://user-images.githubusercontent.com/1132350/139395610-40798130-c924-4046-b5cf-0355f5b4e1ae.PNG)

**Comment by theodorekwok** [comment]
Hi, for point number 2 are you referring to the arrows from XYZDecoder to InstrumentDecoder? This is because from our code XYZDecoder inherits from InstrumentDecoder and they are not instrument types

**Comment by rafaelperes** [comment]
I was referring from XYZDecoder to {abstract}instrument.

**Comment by theodorekwok** [comment]
Our XYZDecoders are only dependent on the instrument. They do not inherit from the instrument class.

**Comment by KVignesh122** [comment]
All diagrams rectified according to TA suggestions.
