### ISSUE TITLE
[PE-D] UG 2.1.4: Expiry date format [add forex]

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S1-CS2113T-T12-1/tp#162]
The format of the expiry date shown in the picture in UG is "2021 10 13".

This does not work in the jar file, but "2021-10-13" would work.

-------------
Labels: `severity.Medium` `type.DocumentationBug`
original: BryanElmer/ped#2

**Comment by theodorekwok** [comment]
<img width="308" alt="ss1" src="https://user-images.githubusercontent.com/60163283/139576638-980f5bb8-c46c-4942-8f61-38ce946484fc.PNG">
Will address this
