### ISSUE TITLE
[PE-D] could consider adding the restrictions for sentiment into the user guide

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S1-CS2113T-T12-1/tp#165]
![image.png](https://raw.githubusercontent.com/rachelkeh/ped/main/files/b8a0a3d0-ef16-4f7a-9f32-d88b11d8a826.png)

![image.png](https://raw.githubusercontent.com/rachelkeh/ped/main/files/fc6630be-95e1-4b7b-93cb-6e1314832732.png)

I was a little confused about what to input for sentiment and I just thought I could input anything in from the looking at the user guide. Turns out I couldn't and the app itself prompted me to input either positive, negative or neutral. Team could consider putting this error prompt into the UG like for the case of the current price parameter to clear any ambiguity with regards to the argument input for sentiment.

-------------
Labels: `severity.Medium` `type.DocumentationBug`
original: rachelkeh/ped#3

**Comment by theodorekwok** [comment]
Will address this
