### ISSUE TITLE
[PE-D] Another small issue regarding the 0

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S1-CS2113T-T12-1/tp#171]
![image.png](https://raw.githubusercontent.com/rachelkeh/ped/main/files/bdeaf255-553e-4a21-9f26-85c7483a0be9.png)

It's pretty similar to the first bug, but just raised this in case the team finds this useful.

-------------
Labels: `type.FeatureFlaw` `severity.VeryLow`
original: rachelkeh/ped#4

**Comment by williamlamjy** [comment]
okay will resolve
