### ISSUE TITLE
[PE-D] Choice of instruments to add is not case sensitive. Perhaps you could change it to allow users to have more freedom?

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S1-CS2113T-T12-1/tp#175]
![bug6.png](https://raw.githubusercontent.com/ThaddeusLim99/ped/main/files/af6d8343-fdef-4a48-b11f-348df84d3132.png)

-------------
Labels: `severity.Low` `type.FeatureFlaw`
original: ThaddeusLim99/ped#3

**Comment by williamlamjy** [comment]
ok will address
