### ISSUE TITLE
[PE-D] Edited remark disappears after reopening the program.

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S1-CS2113T-T12-1/tp#183]
Upon editing the remark of an instrument to any string that begins with ";" [ex: ";hi"], and exiting the program.  
When the program is reopened, the remark section disappears (there is no string under remarks).

-------------
Labels: `type.FunctionalityBug` `severity.High`
original: BryanElmer/ped#8

**Comment by KVignesh122** [comment]
Issue is fixed by PR #164

**Comment by theodorekwok** [comment]
I think this issue is linked to file separator not PR #164
