### ISSUE TITLE
[PE-D] Unable to find words with more than one string

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S1-CS2113T-T12-1/tp#188]
The find feature only allows user to find one string, could be a major issue when users want to find a more descriptive data.
![Screenshot 2021-10-29 at 5.39.11 PM.png](https://raw.githubusercontent.com/LouisLouis19/ped/main/files/d45297d3-0ba2-4ea3-9841-9bf2354b7105.png)

-------------
Labels: `severity.High` `type.FunctionalityBug`
original: LouisLouis19/ped#6

**Comment by KVignesh122** [comment]
Limitation already addressed in UG.
