### ISSUE TITLE
[PE-D] Inconsistent error message for invalid index

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S1-CS2113T-T12-1/tp#190]
Invalid index smaller than 1 has different error message from invalid index which causes overflow. Perhaps could make it more consistent
![Screenshot 2021-10-29 at 5.40.46 PM.png](https://raw.githubusercontent.com/LouisLouis19/ped/main/files/e7c41547-3e8b-45f0-ad23-d774b8e90b05.png)

-------------
Labels: `type.FeatureFlaw` `severity.Low`
original: LouisLouis19/ped#7

**Comment by KVignesh122** [comment]
Error messages are more specified now PR #206
