### ISSUE TITLE
[PE-D] Edit or add command bug

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S1-CS2113T-T12-1/tp#196]
Add and edit command can be used to change all the data for the other parameters. [by inputting information in the name parameter]

-------------
Labels: `type.FunctionalityBug` `severity.High`
original: BryanElmer/ped#11

**Comment by KVignesh122** [comment]
Description of bug not clear.

**Comment by williamlamjy** [comment]
this is the same bug as someone else has mentioned will be addressing this for ref vignesh is the one where they put like AAPL;3.2;positive;; as the name
